// Sample data for testing bulk uploads
export const getSampleConnectionData = () => [
  {
    id: 'sample-1',
    locationCategory: undefined,
    addressLine1: '123 Tech Park',
    addressLine2: 'Building A',
    city: 'Mumbai',
    state: 'Maharashtra',
    pinCode: '400001',
    latitude: '',
    longitude: '',
    bandwidthValue: '100',
    connectionTypes: [
      { type: 'Wireless' as const, isPrimary: true }
    ],
    contactName: 'John Doe',
    contactEmail: 'john.doe@example.com',
    contactPhone: '9876543210',
    vas: [],
    isHub: false,
    linkType: '',
    portType: '',
    portBandwidth: ''
  },
  {
    id: 'sample-2',
    locationCategory: undefined,
    addressLine1: '456 Business Center',
    addressLine2: '',
    city: 'Delhi',
    state: 'Delhi',
    pinCode: '110001',
    latitude: '',
    longitude: '',
    bandwidthValue: '200',
    connectionTypes: [
      { type: 'Fiber' as const, isPrimary: true },
      { type: 'Other ISP' as const, isPrimary: false, serviceProviders: ['Airtel'], primaryProvider: 'Airtel' }
    ],
    contactName: 'Jane Smith',
    contactEmail: 'jane.smith@example.com',
    contactPhone: '9876543211',
    vas: [],
    isHub: false,
    linkType: '',
    portType: '',
    portBandwidth: ''
  },
  {
    id: 'sample-3',
    locationCategory: undefined,
    addressLine1: '789 Corporate Plaza',
    addressLine2: 'Floor 5',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: 'INVALID',
    latitude: '',
    longitude: '',
    bandwidthValue: '500',
    connectionTypes: [],
    contactName: 'Bob Johnson',
    contactEmail: 'invalid-email',
    contactPhone: '123',
    vas: [],
    isHub: false,
    linkType: '',
    portType: '',
    portBandwidth: ''
  },
  {
    id: 'sample-4',
    locationCategory: undefined,
    addressLine1: '',
    addressLine2: '',
    city: '',
    state: 'Tamil Nadu',
    pinCode: '600001',
    latitude: '',
    longitude: '',
    bandwidthValue: '',
    connectionTypes: [
      { type: 'Wireless' as const, isPrimary: true },
      { type: 'Other ISP' as const, isPrimary: false, serviceProviders: ['Vodafone'], primaryProvider: 'Vodafone' }
    ],
    contactName: '',
    contactEmail: 'test@example.com',
    contactPhone: '9876543213',
    vas: [],
    isHub: false,
    linkType: '',
    portType: '',
    portBandwidth: ''
  },
  {
    id: 'sample-5',
    addressLine1: '321 Innovation Hub',
    addressLine2: 'Tower B',
    city: 'Hyderabad',
    state: 'Telangana',
    pinCode: '500001',
    bandwidthValue: '1000',
    connectionTypes: [
      { type: 'Fiber' as const, isPrimary: true }
    ],
    contactName: 'Alice Williams',
    contactEmail: 'alice.williams@example.com',
    contactPhone: '9876543214',
    vas: [],
    isHub: false
  }
];

// Sample services for MDAC flow
export const getSampleMDACServices = () => [
  {
    id: '1',
    address: '123 Tech Park\\nBuilding A\\nMumbai, Maharashtra, 400001',
    addressLine1: '123 Tech Park',
    addressLine2: 'Building A',
    city: 'Mumbai',
    state: 'Maharashtra',
    pinCode: '400001',
    bandwidth: '500 Mbps',
    currentBandwidth: '100 Mbps',
    connectionType: ['Fiber'],
    currentConnectionType: ['Fiber'],
    linkId: 'LINK-001',
    changeType: 'Bandwidth',
    serviceChanges: ['Bandwidth'],
    contactName: 'John Doe',
    contactEmail: 'john.doe@example.com',
    contactPhone: '9876543210',
    status: 'valid' as const
  },
  {
    id: '2',
    address: '456 Business Center\\nDelhi, Delhi, 110001',
    addressLine1: '456 Business Center',
    addressLine2: '',
    city: 'Delhi',
    state: 'Delhi',
    pinCode: '110001',
    bandwidth: '200 Mbps',
    currentBandwidth: '200 Mbps',
    connectionType: ['Fiber'],
    currentConnectionType: ['Wireless'],
    linkId: 'LINK-002',
    changeType: 'LM Type',
    serviceChanges: ['LM Type'],
    contactName: 'Jane Smith',
    contactEmail: 'jane.smith@example.com',
    contactPhone: '9876543211',
    status: 'valid' as const
  },
  {
    id: '3',
    address: '789 Corporate Plaza\\nFloor 5\\nBangalore, Karnataka, INVALID',
    addressLine1: '789 Corporate Plaza',
    addressLine2: 'Floor 5',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: 'INVALID',
    bandwidth: '500 Mbps',
    currentBandwidth: '500 Mbps',
    connectionType: ['Fiber'],
    currentConnectionType: ['Fiber'],
    linkId: 'LINK-003',
    changeType: 'Address',
    serviceChanges: ['Address'],
    contactName: 'Bob Johnson',
    contactEmail: 'invalid-email',
    contactPhone: '123',
    status: 'invalid' as const,
    errors: ['Invalid Pin Code', 'Invalid Contact Email', 'Connection Type is required']
  },
  {
    id: '4',
    address: '-\\nTamil Nadu, 600001',
    addressLine1: '',
    addressLine2: '',
    city: '',
    state: 'Tamil Nadu',
    pinCode: '600001',
    bandwidth: '1 Gbps',
    currentBandwidth: '1 Gbps',
    connectionType: ['Wireless'],
    currentConnectionType: ['Fiber'],
    linkId: 'LINK-004',
    changeType: 'Add Secondary Link',
    serviceChanges: ['Add Link'],
    contactName: '',
    contactEmail: 'test@example.com',
    contactPhone: '9876543213',
    status: 'invalid' as const,
    errors: ['Address Line 1 is required', 'City is required', 'Bandwidth is required', 'Contact Name is required']
  },
  {
    id: '5',
    address: '321 Innovation Hub\\nTower B\\nHyderabad, Telangana, 500001',
    addressLine1: '321 Innovation Hub',
    addressLine2: 'Tower B',
    city: 'Hyderabad',
    state: 'Telangana',
    pinCode: '500001',
    bandwidth: '1 Gbps',
    currentBandwidth: '100 Mbps',
    connectionType: ['Fiber'],
    currentConnectionType: ['Wireless'],
    linkId: 'LINK-005',
    changeType: 'Bandwidth,LM Type',
    serviceChanges: ['Bandwidth', 'LM Type'],
    contactName: 'Alice Williams',
    contactEmail: 'alice.williams@example.com',
    contactPhone: '9876543214',
    status: 'valid' as const
  }
];
